package com.bank.common.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

/**
 * Holder class for account-related DTO records used across microservices.
 * Keeping DTOs in one module prevents contract drift between services.
 */
public final class AccountDtos {

    /**
     * Private constructor prevents instantiation because this class only groups DTO records.
     */
    private AccountDtos() {
    }

    /**
     * Request model used when a client asks account-service to create a new bank account.
     *
     * @param customerName owner name displayed by the bank.
     * @param accountType  account category such as SAVINGS or CURRENT.
     * @param openingBalance initial amount deposited at account opening.
     */
    public record CreateAccountRequest(
            @NotBlank(message = "Customer name is required") String customerName,
            @NotBlank(message = "Account type is required") String accountType,
            @NotNull(message = "Opening balance is required") @Positive(message = "Opening balance must be positive")
            Double openingBalance) {
    }

    /**
     * Response model returned by account-service to frontend and other microservices.
     *
     * @param id unique account identifier generated by database.
     * @param customerName owner name.
     * @param accountType account category.
     * @param balance current account balance.
     */
    public record AccountResponse(Long id, String customerName, String accountType, Double balance) {
    }

    /**
     * Command model sent by transaction-service to account-service when updating a balance.
     *
     * @param accountId account to be updated.
     * @param amount signed amount, positive for credit and negative for debit.
     */
    public record BalanceUpdateRequest(
            @NotNull(message = "Account id is required") Long accountId,
            @NotNull(message = "Amount is required") Double amount) {
    }
}
